### ISSUE TITLE
Facing an error with nixpkgs-fmt: unrecognised flag '-c'

### ISSUE THREAD

**Issue by snawaz** [workflow/nix-shell-action#197]
Hey @workflow,  I didn't know you are the creator of this cool tool!!  

We're using it, though slightly older version (469e057ef6ae645b60473cc006a5683ef0d6d5ce) and we're getting this error. Not sure if you have seen and fixed this... or maybe it's a problem with our environment 🤔 

![image](https://user-images.githubusercontent.com/1185906/142952682-0affa03b-d8b9-44a2-be6f-def92daf2023.png)

**Comment by workflow** [comment]
Hey @snawaz, long time no see :) 
 if you switch to `v3` (608eb20401e12c82b204e8e2c6a8b0eebfb5407c) it should work
 
 This problem is introduced by switching to `nix 2.4+` but not updating the action, so alternatively you could also switch back to a non-experimental nix (most likely by pinning the `nix-install` action)

Let me know if that helps!

**Comment by snawaz** [comment]
> if you switch to `v3` ([608eb20](https://github.com/workflow/nix-shell-action/commit/608eb20401e12c82b204e8e2c6a8b0eebfb5407c)) it should work

Haha, yes. I kinda guessed that myself from the `Releases` tab. It indeed works. Thanks for the great work. 😄 

> This problem is introduced by switching to nix 2.4+ but not updating the action, so alternatively you could also switch back to a non-experimental nix (most likely by pinning the nix-install action)

ah, I see. I didn't understand the cause of the problem though. Thanks for explaining this part as well. 

_(closing this issue)_.
